language: scala

sudo: required
dist: trusty

scala:
- 2.11.8

notifications:
  email:
  - dembol@devesion.com

branches:
  only:
  - master

jdk:
- oraclejdk8

matrix:
  include:
  - scala: 2.12.0
    jdk: oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script: eval "sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport coverageAggregate coveralls"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot